import { ExerciseDB } from '../types';

export const EXERCISES: ExerciseDB[] = [
  // CHEST
  { name: 'Barbell Bench Press', muscle_group: 'Chest', category: 'Compound', equipment: 'Barbell' },
  { name: 'Incline Barbell Bench Press', muscle_group: 'Chest', category: 'Compound', equipment: 'Barbell' },
  { name: 'Decline Barbell Bench Press', muscle_group: 'Chest', category: 'Compound', equipment: 'Barbell' },
  { name: 'Dumbbell Bench Press', muscle_group: 'Chest', category: 'Compound', equipment: 'Dumbbell' },
  { name: 'Incline Dumbbell Bench Press', muscle_group: 'Chest', category: 'Compound', equipment: 'Dumbbell' },
  { name: 'Decline Dumbbell Bench Press', muscle_group: 'Chest', category: 'Compound', equipment: 'Dumbbell' },
  { name: 'Dumbbell Flyes', muscle_group: 'Chest', category: 'Isolation', equipment: 'Dumbbell' },
  { name: 'Incline Dumbbell Flyes', muscle_group: 'Chest', category: 'Isolation', equipment: 'Dumbbell' },
  { name: 'Cable Flyes', muscle_group: 'Chest', category: 'Isolation', equipment: 'Cable' },
  { name: 'Low Cable Flyes', muscle_group: 'Chest', category: 'Isolation', equipment: 'Cable' },
  { name: 'High Cable Flyes', muscle_group: 'Chest', category: 'Isolation', equipment: 'Cable' },
  { name: 'Pec Deck Machine', muscle_group: 'Chest', category: 'Isolation', equipment: 'Machine' },
  { name: 'Machine Chest Press', muscle_group: 'Chest', category: 'Compound', equipment: 'Machine' },
  { name: 'Incline Machine Press', muscle_group: 'Chest', category: 'Compound', equipment: 'Machine' },
  { name: 'Push-ups', muscle_group: 'Chest', category: 'Compound', equipment: 'Bodyweight' },
  { name: 'Diamond Push-ups', muscle_group: 'Chest', category: 'Compound', equipment: 'Bodyweight' },
  { name: 'Weighted Dips (Chest)', muscle_group: 'Chest', category: 'Compound', equipment: 'Bodyweight' },
  { name: 'Dips (Chest)', muscle_group: 'Chest', category: 'Compound', equipment: 'Bodyweight' },
  { name: 'Landmine Press', muscle_group: 'Chest', category: 'Compound', equipment: 'Barbell' },
  { name: 'Svend Press', muscle_group: 'Chest', category: 'Isolation', equipment: 'Plate' },
  { name: 'Close Grip Bench Press', muscle_group: 'Chest', category: 'Compound', equipment: 'Barbell' },
  { name: 'Smith Machine Bench Press', muscle_group: 'Chest', category: 'Compound', equipment: 'Machine' },
  { name: 'Smith Machine Incline Press', muscle_group: 'Chest', category: 'Compound', equipment: 'Machine' },
  { name: 'Chest Dip Machine', muscle_group: 'Chest', category: 'Compound', equipment: 'Machine' },
  { name: 'Floor Press', muscle_group: 'Chest', category: 'Compound', equipment: 'Barbell' },

  // BACK
  { name: 'Deadlift', muscle_group: 'Back', category: 'Compound', equipment: 'Barbell' },
  { name: 'Conventional Deadlift', muscle_group: 'Back', category: 'Compound', equipment: 'Barbell' },
  { name: 'Sumo Deadlift', muscle_group: 'Back', category: 'Compound', equipment: 'Barbell' },
  { name: 'Romanian Deadlift', muscle_group: 'Back', category: 'Compound', equipment: 'Barbell' },
  { name: 'Barbell Row', muscle_group: 'Back', category: 'Compound', equipment: 'Barbell' },
  { name: 'Pendlay Row', muscle_group: 'Back', category: 'Compound', equipment: 'Barbell' },
  { name: 'T-Bar Row', muscle_group: 'Back', category: 'Compound', equipment: 'Barbell' },
  { name: 'Dumbbell Row', muscle_group: 'Back', category: 'Compound', equipment: 'Dumbbell' },
  { name: 'One Arm Dumbbell Row', muscle_group: 'Back', category: 'Compound', equipment: 'Dumbbell' },
  { name: 'Seated Cable Row', muscle_group: 'Back', category: 'Compound', equipment: 'Cable' },
  { name: 'Wide Grip Cable Row', muscle_group: 'Back', category: 'Compound', equipment: 'Cable' },
  { name: 'Lat Pulldown', muscle_group: 'Back', category: 'Compound', equipment: 'Cable' },
  { name: 'Wide Grip Lat Pulldown', muscle_group: 'Back', category: 'Compound', equipment: 'Cable' },
  { name: 'Close Grip Lat Pulldown', muscle_group: 'Back', category: 'Compound', equipment: 'Cable' },
  { name: 'Reverse Grip Lat Pulldown', muscle_group: 'Back', category: 'Compound', equipment: 'Cable' },
  { name: 'Pull-ups', muscle_group: 'Back', category: 'Compound', equipment: 'Bodyweight' },
  { name: 'Chin-ups', muscle_group: 'Back', category: 'Compound', equipment: 'Bodyweight' },
  { name: 'Weighted Pull-ups', muscle_group: 'Back', category: 'Compound', equipment: 'Bodyweight' },
  { name: 'Neutral Grip Pull-ups', muscle_group: 'Back', category: 'Compound', equipment: 'Bodyweight' },
  { name: 'Machine Row', muscle_group: 'Back', category: 'Compound', equipment: 'Machine' },
  { name: 'Chest Supported Row', muscle_group: 'Back', category: 'Compound', equipment: 'Dumbbell' },
  { name: 'Meadows Row', muscle_group: 'Back', category: 'Compound', equipment: 'Barbell' },
  { name: 'Seal Row', muscle_group: 'Back', category: 'Compound', equipment: 'Barbell' },
  { name: 'Straight Arm Pulldown', muscle_group: 'Back', category: 'Isolation', equipment: 'Cable' },
  { name: 'Cable Pullover', muscle_group: 'Back', category: 'Isolation', equipment: 'Cable' },
  { name: 'Dumbbell Pullover', muscle_group: 'Back', category: 'Isolation', equipment: 'Dumbbell' },
  { name: 'Rack Pull', muscle_group: 'Back', category: 'Compound', equipment: 'Barbell' },
  { name: 'Good Morning', muscle_group: 'Back', category: 'Compound', equipment: 'Barbell' },
  { name: 'Hyperextension', muscle_group: 'Back', category: 'Isolation', equipment: 'Bodyweight' },
  { name: 'Inverted Row', muscle_group: 'Back', category: 'Compound', equipment: 'Bodyweight' },
  { name: 'Smith Machine Row', muscle_group: 'Back', category: 'Compound', equipment: 'Machine' },
  { name: 'Helms Row', muscle_group: 'Back', category: 'Compound', equipment: 'Dumbbell' },

  // SHOULDERS
  { name: 'Overhead Press', muscle_group: 'Shoulders', category: 'Compound', equipment: 'Barbell' },
  { name: 'Military Press', muscle_group: 'Shoulders', category: 'Compound', equipment: 'Barbell' },
  { name: 'Seated Dumbbell Press', muscle_group: 'Shoulders', category: 'Compound', equipment: 'Dumbbell' },
  { name: 'Standing Dumbbell Press', muscle_group: 'Shoulders', category: 'Compound', equipment: 'Dumbbell' },
  { name: 'Arnold Press', muscle_group: 'Shoulders', category: 'Compound', equipment: 'Dumbbell' },
  { name: 'Dumbbell Lateral Raise', muscle_group: 'Shoulders', category: 'Isolation', equipment: 'Dumbbell' },
  { name: 'Cable Lateral Raise', muscle_group: 'Shoulders', category: 'Isolation', equipment: 'Cable' },
  { name: 'Machine Lateral Raise', muscle_group: 'Shoulders', category: 'Isolation', equipment: 'Machine' },
  { name: 'Front Raise', muscle_group: 'Shoulders', category: 'Isolation', equipment: 'Dumbbell' },
  { name: 'Cable Front Raise', muscle_group: 'Shoulders', category: 'Isolation', equipment: 'Cable' },
  { name: 'Plate Front Raise', muscle_group: 'Shoulders', category: 'Isolation', equipment: 'Plate' },
  { name: 'Face Pull', muscle_group: 'Shoulders', category: 'Isolation', equipment: 'Cable' },
  { name: 'Reverse Pec Deck', muscle_group: 'Shoulders', category: 'Isolation', equipment: 'Machine' },
  { name: 'Rear Delt Fly', muscle_group: 'Shoulders', category: 'Isolation', equipment: 'Dumbbell' },
  { name: 'Cable Rear Delt Fly', muscle_group: 'Shoulders', category: 'Isolation', equipment: 'Cable' },
  { name: 'Upright Row', muscle_group: 'Shoulders', category: 'Compound', equipment: 'Barbell' },
  { name: 'Dumbbell Upright Row', muscle_group: 'Shoulders', category: 'Compound', equipment: 'Dumbbell' },
  { name: 'Machine Shoulder Press', muscle_group: 'Shoulders', category: 'Compound', equipment: 'Machine' },
  { name: 'Smith Machine Shoulder Press', muscle_group: 'Shoulders', category: 'Compound', equipment: 'Machine' },
  { name: 'Push Press', muscle_group: 'Shoulders', category: 'Compound', equipment: 'Barbell' },
  { name: 'Behind Neck Press', muscle_group: 'Shoulders', category: 'Compound', equipment: 'Barbell' },
  { name: 'Lu Raise', muscle_group: 'Shoulders', category: 'Isolation', equipment: 'Dumbbell' },
  { name: 'Bradford Press', muscle_group: 'Shoulders', category: 'Compound', equipment: 'Barbell' },
  { name: 'Landmine Lateral Raise', muscle_group: 'Shoulders', category: 'Isolation', equipment: 'Barbell' },
  { name: 'Bent Over Rear Delt Fly', muscle_group: 'Shoulders', category: 'Isolation', equipment: 'Dumbbell' },

  // BICEPS
  { name: 'Barbell Curl', muscle_group: 'Biceps', category: 'Isolation', equipment: 'Barbell' },
  { name: 'EZ Bar Curl', muscle_group: 'Biceps', category: 'Isolation', equipment: 'Barbell' },
  { name: 'Dumbbell Curl', muscle_group: 'Biceps', category: 'Isolation', equipment: 'Dumbbell' },
  { name: 'Alternating Dumbbell Curl', muscle_group: 'Biceps', category: 'Isolation', equipment: 'Dumbbell' },
  { name: 'Hammer Curl', muscle_group: 'Biceps', category: 'Isolation', equipment: 'Dumbbell' },
  { name: 'Incline Dumbbell Curl', muscle_group: 'Biceps', category: 'Isolation', equipment: 'Dumbbell' },
  { name: 'Concentration Curl', muscle_group: 'Biceps', category: 'Isolation', equipment: 'Dumbbell' },
  { name: 'Preacher Curl', muscle_group: 'Biceps', category: 'Isolation', equipment: 'Barbell' },
  { name: 'Dumbbell Preacher Curl', muscle_group: 'Biceps', category: 'Isolation', equipment: 'Dumbbell' },
  { name: 'Machine Preacher Curl', muscle_group: 'Biceps', category: 'Isolation', equipment: 'Machine' },
  { name: 'Cable Curl', muscle_group: 'Biceps', category: 'Isolation', equipment: 'Cable' },
  { name: 'Cable Hammer Curl', muscle_group: 'Biceps', category: 'Isolation', equipment: 'Cable' },
  { name: 'Spider Curl', muscle_group: 'Biceps', category: 'Isolation', equipment: 'Dumbbell' },
  { name: 'Bayesian Curl', muscle_group: 'Biceps', category: 'Isolation', equipment: 'Cable' },
  { name: 'Cross Body Curl', muscle_group: 'Biceps', category: 'Isolation', equipment: 'Dumbbell' },
  { name: 'Reverse Curl', muscle_group: 'Biceps', category: 'Isolation', equipment: 'Barbell' },
  { name: '21s Curl', muscle_group: 'Biceps', category: 'Isolation', equipment: 'Barbell' },
  { name: 'Machine Curl', muscle_group: 'Biceps', category: 'Isolation', equipment: 'Machine' },
  { name: 'Zottman Curl', muscle_group: 'Biceps', category: 'Isolation', equipment: 'Dumbbell' },
  { name: 'Drag Curl', muscle_group: 'Biceps', category: 'Isolation', equipment: 'Barbell' },

  // TRICEPS
  { name: 'Tricep Pushdown', muscle_group: 'Triceps', category: 'Isolation', equipment: 'Cable' },
  { name: 'Rope Pushdown', muscle_group: 'Triceps', category: 'Isolation', equipment: 'Cable' },
  { name: 'Overhead Tricep Extension', muscle_group: 'Triceps', category: 'Isolation', equipment: 'Cable' },
  { name: 'Dumbbell Overhead Extension', muscle_group: 'Triceps', category: 'Isolation', equipment: 'Dumbbell' },
  { name: 'Skull Crushers', muscle_group: 'Triceps', category: 'Isolation', equipment: 'Barbell' },
  { name: 'EZ Bar Skull Crushers', muscle_group: 'Triceps', category: 'Isolation', equipment: 'Barbell' },
  { name: 'Dumbbell Skull Crushers', muscle_group: 'Triceps', category: 'Isolation', equipment: 'Dumbbell' },
  { name: 'Tricep Dips', muscle_group: 'Triceps', category: 'Compound', equipment: 'Bodyweight' },
  { name: 'Bench Dips', muscle_group: 'Triceps', category: 'Compound', equipment: 'Bodyweight' },
  { name: 'Tricep Kickback', muscle_group: 'Triceps', category: 'Isolation', equipment: 'Dumbbell' },
  { name: 'Cable Kickback', muscle_group: 'Triceps', category: 'Isolation', equipment: 'Cable' },
  { name: 'JM Press', muscle_group: 'Triceps', category: 'Compound', equipment: 'Barbell' },
  { name: 'Machine Tricep Extension', muscle_group: 'Triceps', category: 'Isolation', equipment: 'Machine' },
  { name: 'Diamond Push-ups', muscle_group: 'Triceps', category: 'Compound', equipment: 'Bodyweight' },
  { name: 'Overhead Rope Extension', muscle_group: 'Triceps', category: 'Isolation', equipment: 'Cable' },
  { name: 'Single Arm Pushdown', muscle_group: 'Triceps', category: 'Isolation', equipment: 'Cable' },
  { name: 'Tate Press', muscle_group: 'Triceps', category: 'Isolation', equipment: 'Dumbbell' },
  { name: 'French Press', muscle_group: 'Triceps', category: 'Isolation', equipment: 'Barbell' },

  // QUADS
  { name: 'Barbell Squat', muscle_group: 'Quads', category: 'Compound', equipment: 'Barbell' },
  { name: 'Front Squat', muscle_group: 'Quads', category: 'Compound', equipment: 'Barbell' },
  { name: 'Goblet Squat', muscle_group: 'Quads', category: 'Compound', equipment: 'Dumbbell' },
  { name: 'Hack Squat', muscle_group: 'Quads', category: 'Compound', equipment: 'Machine' },
  { name: 'Leg Press', muscle_group: 'Quads', category: 'Compound', equipment: 'Machine' },
  { name: 'Leg Extension', muscle_group: 'Quads', category: 'Isolation', equipment: 'Machine' },
  { name: 'Walking Lunges', muscle_group: 'Quads', category: 'Compound', equipment: 'Dumbbell' },
  { name: 'Reverse Lunges', muscle_group: 'Quads', category: 'Compound', equipment: 'Dumbbell' },
  { name: 'Bulgarian Split Squat', muscle_group: 'Quads', category: 'Compound', equipment: 'Dumbbell' },
  { name: 'Step Ups', muscle_group: 'Quads', category: 'Compound', equipment: 'Dumbbell' },
  { name: 'Sissy Squat', muscle_group: 'Quads', category: 'Isolation', equipment: 'Bodyweight' },
  { name: 'Smith Machine Squat', muscle_group: 'Quads', category: 'Compound', equipment: 'Machine' },
  { name: 'Pendulum Squat', muscle_group: 'Quads', category: 'Compound', equipment: 'Machine' },
  { name: 'Belt Squat', muscle_group: 'Quads', category: 'Compound', equipment: 'Machine' },
  { name: 'Wall Sit', muscle_group: 'Quads', category: 'Isolation', equipment: 'Bodyweight' },
  { name: 'Single Leg Press', muscle_group: 'Quads', category: 'Compound', equipment: 'Machine' },
  { name: 'Barbell Lunges', muscle_group: 'Quads', category: 'Compound', equipment: 'Barbell' },
  { name: 'Safety Bar Squat', muscle_group: 'Quads', category: 'Compound', equipment: 'Barbell' },
  { name: 'Narrow Stance Leg Press', muscle_group: 'Quads', category: 'Compound', equipment: 'Machine' },
  { name: 'Pistol Squat', muscle_group: 'Quads', category: 'Compound', equipment: 'Bodyweight' },

  // HAMSTRINGS
  { name: 'Romanian Deadlift', muscle_group: 'Hamstrings', category: 'Compound', equipment: 'Barbell' },
  { name: 'Stiff Leg Deadlift', muscle_group: 'Hamstrings', category: 'Compound', equipment: 'Barbell' },
  { name: 'Dumbbell Romanian Deadlift', muscle_group: 'Hamstrings', category: 'Compound', equipment: 'Dumbbell' },
  { name: 'Single Leg Romanian Deadlift', muscle_group: 'Hamstrings', category: 'Compound', equipment: 'Dumbbell' },
  { name: 'Lying Leg Curl', muscle_group: 'Hamstrings', category: 'Isolation', equipment: 'Machine' },
  { name: 'Seated Leg Curl', muscle_group: 'Hamstrings', category: 'Isolation', equipment: 'Machine' },
  { name: 'Standing Leg Curl', muscle_group: 'Hamstrings', category: 'Isolation', equipment: 'Machine' },
  { name: 'Nordic Curl', muscle_group: 'Hamstrings', category: 'Compound', equipment: 'Bodyweight' },
  { name: 'Good Morning', muscle_group: 'Hamstrings', category: 'Compound', equipment: 'Barbell' },
  { name: 'Glute Ham Raise', muscle_group: 'Hamstrings', category: 'Compound', equipment: 'Machine' },
  { name: 'Cable Pull Through', muscle_group: 'Hamstrings', category: 'Isolation', equipment: 'Cable' },
  { name: 'Swiss Ball Leg Curl', muscle_group: 'Hamstrings', category: 'Isolation', equipment: 'Bodyweight' },
  { name: 'Kettlebell Swing', muscle_group: 'Hamstrings', category: 'Compound', equipment: 'Kettlebell' },

  // GLUTES
  { name: 'Hip Thrust', muscle_group: 'Glutes', category: 'Compound', equipment: 'Barbell' },
  { name: 'Barbell Hip Thrust', muscle_group: 'Glutes', category: 'Compound', equipment: 'Barbell' },
  { name: 'Dumbbell Hip Thrust', muscle_group: 'Glutes', category: 'Compound', equipment: 'Dumbbell' },
  { name: 'Single Leg Hip Thrust', muscle_group: 'Glutes', category: 'Compound', equipment: 'Bodyweight' },
  { name: 'Glute Bridge', muscle_group: 'Glutes', category: 'Isolation', equipment: 'Bodyweight' },
  { name: 'Cable Glute Kickback', muscle_group: 'Glutes', category: 'Isolation', equipment: 'Cable' },
  { name: 'Machine Glute Kickback', muscle_group: 'Glutes', category: 'Isolation', equipment: 'Machine' },
  { name: 'Sumo Squat', muscle_group: 'Glutes', category: 'Compound', equipment: 'Dumbbell' },
  { name: 'Cable Pull Through', muscle_group: 'Glutes', category: 'Isolation', equipment: 'Cable' },
  { name: 'Hip Abduction Machine', muscle_group: 'Glutes', category: 'Isolation', equipment: 'Machine' },
  { name: 'Hip Adduction Machine', muscle_group: 'Glutes', category: 'Isolation', equipment: 'Machine' },
  { name: 'Frog Pumps', muscle_group: 'Glutes', category: 'Isolation', equipment: 'Bodyweight' },
  { name: 'Banded Clamshells', muscle_group: 'Glutes', category: 'Isolation', equipment: 'Band' },
  { name: 'Cable Hip Abduction', muscle_group: 'Glutes', category: 'Isolation', equipment: 'Cable' },

  // CALVES
  { name: 'Standing Calf Raise', muscle_group: 'Calves', category: 'Isolation', equipment: 'Machine' },
  { name: 'Seated Calf Raise', muscle_group: 'Calves', category: 'Isolation', equipment: 'Machine' },
  { name: 'Smith Machine Calf Raise', muscle_group: 'Calves', category: 'Isolation', equipment: 'Machine' },
  { name: 'Leg Press Calf Raise', muscle_group: 'Calves', category: 'Isolation', equipment: 'Machine' },
  { name: 'Donkey Calf Raise', muscle_group: 'Calves', category: 'Isolation', equipment: 'Machine' },
  { name: 'Single Leg Calf Raise', muscle_group: 'Calves', category: 'Isolation', equipment: 'Bodyweight' },
  { name: 'Bodyweight Calf Raise', muscle_group: 'Calves', category: 'Isolation', equipment: 'Bodyweight' },
  { name: 'Tibialis Raise', muscle_group: 'Calves', category: 'Isolation', equipment: 'Bodyweight' },

  // CORE
  { name: 'Plank', muscle_group: 'Core', category: 'Isolation', equipment: 'Bodyweight' },
  { name: 'Side Plank', muscle_group: 'Core', category: 'Isolation', equipment: 'Bodyweight' },
  { name: 'Ab Wheel Rollout', muscle_group: 'Core', category: 'Compound', equipment: 'Bodyweight' },
  { name: 'Hanging Leg Raise', muscle_group: 'Core', category: 'Compound', equipment: 'Bodyweight' },
  { name: 'Hanging Knee Raise', muscle_group: 'Core', category: 'Compound', equipment: 'Bodyweight' },
  { name: 'Cable Crunch', muscle_group: 'Core', category: 'Isolation', equipment: 'Cable' },
  { name: 'Machine Crunch', muscle_group: 'Core', category: 'Isolation', equipment: 'Machine' },
  { name: 'Decline Sit-ups', muscle_group: 'Core', category: 'Isolation', equipment: 'Bodyweight' },
  { name: 'Russian Twist', muscle_group: 'Core', category: 'Isolation', equipment: 'Bodyweight' },
  { name: 'Bicycle Crunch', muscle_group: 'Core', category: 'Isolation', equipment: 'Bodyweight' },
  { name: 'Dragon Flag', muscle_group: 'Core', category: 'Compound', equipment: 'Bodyweight' },
  { name: 'Pallof Press', muscle_group: 'Core', category: 'Isolation', equipment: 'Cable' },
  { name: 'Dead Bug', muscle_group: 'Core', category: 'Isolation', equipment: 'Bodyweight' },
  { name: 'Bird Dog', muscle_group: 'Core', category: 'Isolation', equipment: 'Bodyweight' },
  { name: 'Decline Crunch', muscle_group: 'Core', category: 'Isolation', equipment: 'Bodyweight' },
  { name: 'V-ups', muscle_group: 'Core', category: 'Isolation', equipment: 'Bodyweight' },
  { name: 'Mountain Climbers', muscle_group: 'Core', category: 'Compound', equipment: 'Bodyweight' },
  { name: 'Toe Touches', muscle_group: 'Core', category: 'Isolation', equipment: 'Bodyweight' },
  { name: 'Flutter Kicks', muscle_group: 'Core', category: 'Isolation', equipment: 'Bodyweight' },
  { name: 'Leg Raises', muscle_group: 'Core', category: 'Isolation', equipment: 'Bodyweight' },
  { name: 'Woodchoppers', muscle_group: 'Core', category: 'Compound', equipment: 'Cable' },
  { name: 'Cable Rotation', muscle_group: 'Core', category: 'Isolation', equipment: 'Cable' },
  { name: 'Weighted Plank', muscle_group: 'Core', category: 'Isolation', equipment: 'Plate' },
  { name: 'L-Sit', muscle_group: 'Core', category: 'Compound', equipment: 'Bodyweight' },
  { name: 'Reverse Crunch', muscle_group: 'Core', category: 'Isolation', equipment: 'Bodyweight' },
  { name: 'Copenhagen Plank', muscle_group: 'Core', category: 'Isolation', equipment: 'Bodyweight' },

  // TRAPS
  { name: 'Barbell Shrugs', muscle_group: 'Traps', category: 'Isolation', equipment: 'Barbell' },
  { name: 'Dumbbell Shrugs', muscle_group: 'Traps', category: 'Isolation', equipment: 'Dumbbell' },
  { name: 'Trap Bar Shrugs', muscle_group: 'Traps', category: 'Isolation', equipment: 'Barbell' },
  { name: 'Smith Machine Shrugs', muscle_group: 'Traps', category: 'Isolation', equipment: 'Machine' },
  { name: 'Cable Shrugs', muscle_group: 'Traps', category: 'Isolation', equipment: 'Cable' },
  { name: 'Farmers Walk', muscle_group: 'Traps', category: 'Compound', equipment: 'Dumbbell' },
  { name: 'Face Pull', muscle_group: 'Traps', category: 'Isolation', equipment: 'Cable' },

  // FOREARMS
  { name: 'Wrist Curl', muscle_group: 'Forearms', category: 'Isolation', equipment: 'Barbell' },
  { name: 'Reverse Wrist Curl', muscle_group: 'Forearms', category: 'Isolation', equipment: 'Barbell' },
  { name: 'Dumbbell Wrist Curl', muscle_group: 'Forearms', category: 'Isolation', equipment: 'Dumbbell' },
  { name: 'Reverse Barbell Curl', muscle_group: 'Forearms', category: 'Isolation', equipment: 'Barbell' },
  { name: 'Farmers Walk', muscle_group: 'Forearms', category: 'Compound', equipment: 'Dumbbell' },
  { name: 'Plate Pinch', muscle_group: 'Forearms', category: 'Isolation', equipment: 'Plate' },
  { name: 'Dead Hang', muscle_group: 'Forearms', category: 'Isolation', equipment: 'Bodyweight' },
  { name: 'Gripper', muscle_group: 'Forearms', category: 'Isolation', equipment: 'Other' },
  { name: 'Behind Back Wrist Curl', muscle_group: 'Forearms', category: 'Isolation', equipment: 'Barbell' },
  { name: 'Towel Pull-up', muscle_group: 'Forearms', category: 'Compound', equipment: 'Bodyweight' },

  // CARDIO & FULL BODY
  { name: 'Treadmill Running', muscle_group: 'Cardio', category: 'Cardio', equipment: 'Machine' },
  { name: 'Treadmill Walking', muscle_group: 'Cardio', category: 'Cardio', equipment: 'Machine' },
  { name: 'Incline Treadmill Walk', muscle_group: 'Cardio', category: 'Cardio', equipment: 'Machine' },
  { name: 'Cycling', muscle_group: 'Cardio', category: 'Cardio', equipment: 'Machine' },
  { name: 'Stationary Bike', muscle_group: 'Cardio', category: 'Cardio', equipment: 'Machine' },
  { name: 'Rowing Machine', muscle_group: 'Cardio', category: 'Cardio', equipment: 'Machine' },
  { name: 'Elliptical', muscle_group: 'Cardio', category: 'Cardio', equipment: 'Machine' },
  { name: 'Stair Climber', muscle_group: 'Cardio', category: 'Cardio', equipment: 'Machine' },
  { name: 'Jump Rope', muscle_group: 'Cardio', category: 'Cardio', equipment: 'Other' },
  { name: 'Burpees', muscle_group: 'Cardio', category: 'Cardio', equipment: 'Bodyweight' },
  { name: 'Battle Ropes', muscle_group: 'Cardio', category: 'Cardio', equipment: 'Other' },
  { name: 'Box Jumps', muscle_group: 'Cardio', category: 'Cardio', equipment: 'Other' },
  { name: 'Sled Push', muscle_group: 'Cardio', category: 'Cardio', equipment: 'Other' },
  { name: 'Swimming', muscle_group: 'Cardio', category: 'Cardio', equipment: 'Other' },
  { name: 'Sprint Intervals', muscle_group: 'Cardio', category: 'Cardio', equipment: 'Bodyweight' },

  // OLYMPIC LIFTS
  { name: 'Clean and Jerk', muscle_group: 'Full Body', category: 'Compound', equipment: 'Barbell' },
  { name: 'Snatch', muscle_group: 'Full Body', category: 'Compound', equipment: 'Barbell' },
  { name: 'Power Clean', muscle_group: 'Full Body', category: 'Compound', equipment: 'Barbell' },
  { name: 'Hang Clean', muscle_group: 'Full Body', category: 'Compound', equipment: 'Barbell' },
  { name: 'Clean Pull', muscle_group: 'Full Body', category: 'Compound', equipment: 'Barbell' },
  { name: 'Snatch Pull', muscle_group: 'Full Body', category: 'Compound', equipment: 'Barbell' },
  { name: 'Thruster', muscle_group: 'Full Body', category: 'Compound', equipment: 'Barbell' },
  { name: 'Dumbbell Thruster', muscle_group: 'Full Body', category: 'Compound', equipment: 'Dumbbell' },
  { name: 'Turkish Get Up', muscle_group: 'Full Body', category: 'Compound', equipment: 'Kettlebell' },
  { name: 'Man Maker', muscle_group: 'Full Body', category: 'Compound', equipment: 'Dumbbell' },
];

export function searchExercises(query: string, muscleGroup?: string): ExerciseDB[] {
  let filtered = EXERCISES;
  if (muscleGroup) {
    filtered = filtered.filter(e => e.muscle_group === muscleGroup);
  }
  if (query) {
    const lowerQuery = query.toLowerCase();
    filtered = filtered.filter(e =>
      e.name.toLowerCase().includes(lowerQuery) ||
      e.muscle_group.toLowerCase().includes(lowerQuery) ||
      e.equipment.toLowerCase().includes(lowerQuery)
    );
  }
  return filtered.slice(0, 50);
}

export function getExercisesByMuscle(muscleGroup: string): ExerciseDB[] {
  return EXERCISES.filter(e => e.muscle_group === muscleGroup);
}

export function getMuscleGroups(): string[] {
  return [...new Set(EXERCISES.map(e => e.muscle_group))];
}
